# Configurations
title:            chirantandip
longtitle:        chirantandip
author:           chirantandip
email:            chirantandipmahanta@gmail.com
description: >
  Build Jekyll site.

version:          1.0
gitbook_version:  3.2.3

url:              'https://chirantandip.github.io'
baseurl:          '/'
rss:              RSS

# markdown render engine.
markdown:         kramdown

syntax_highlighter_style: colorful

markdown_ext:  mkdn,mkd,md

# Permalinks
permalink:  /:title
