remote_theme: chirantandip/jekyll-gitbook

# Site settings
title: Your GitHub Page Title
description: Your GitHub Page Description


# Custom Fonts
fonts:
  - name: "Computer Modern Sans Serif"
    css:
      - "https://fonts.googleapis.com/css2?family=Computer+Modern+Sans+Serif&display=swap"
