theme: jekyll-theme-gitbook

# Site settings
title: Your GitHub Page Title
description: Your GitHub Page Description


# Custom Fonts
fonts:
  - name: "Computer Modern Sans Serif"
    css:
      - "https://fonts.googleapis.com/css2?family=Computer+Modern+Sans+Serif&display=swap"

# Plugins
plugins:
  - jekyll-seo-tag
