# Configurations
title:            Chirantandip
longtitle:        Chirantandip main file
author:           Chirantandip Mahanta
email:            chirantandipmahanta@gmail.com
description: >
  Chirantandip's webpage.

version:          1.0
gitbook_version:  3.2.3

url:              'https://chirantandip.github.io'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
#remote_theme: sighingnow/jekyll-gitbook
#theme: jekyll-theme-basically-basic
#theme: jekyll-theme-minimal 
theme: documentation-theme-jekyll

# markdown render engine.
markdown:  pandoc
pandoc:
  extensions:
    - filter: mermaid-filter
    - filter: mathjax-pandoc-filter
    - '-Mmathjax.centerDisplayMath' # center display math

syntax_highlighter_style: colorful

markdown_ext:  mkd,md

# Permalinks
permalink:  /:categories/:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:title/

destination:      ./_site
incremental:      true
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
